version: '3'

services:
  operator:
    container_name: operator
    build:
      context: ./
      dockerfile: ./Dockerfile
    user: node
    working_dir: /home/node/operator/web
    volumes:
      - ./web:/home/node/operator/web
    command: |
      bash -c "npm ci && npm run dev"
    ports:
      - 5173:5173
    tty: true